### ISSUE TITLE
请问最后的上传类怎么填写

### ISSUE THREAD

**Issue by liyansum** [sudoskys/BotPicUploader#1]
在main.py里修改了bot的token还有headers userid,最后的上传类不知道怎么填写，部分注释是否应该删去，例如post那里？
小白不太懂，感谢。

**Comment by sudoskys** [comment]
class test(object):

按照这个类的用例写。我下午重新修改一下，使其更于易用，插件化

**Comment by liyansum** [comment]
懂了 发现很多图床的接口都不太一样 后面修改了请求弄好了
